"""
tests/test_clearance_template.py

Unit tests for ui/pages/report._build_clearance_template().

Covers:
  - All fields present → full populated template
  - All optional stages None → fallback strings, no crash
  - Individual stage absent (pop, comp, aq, legal)
  - Title/artist missing from metadata → Unknown defaults
"""
from __future__ import annotations

import pytest

from core.models import (
    AnalysisResult,
    AudioBuffer,
    AudioQualityResult,
    ComplianceReport,
    EnergyEvolutionResult,
    IntroResult,
    LegalLinks,
    PopularityResult,
    StingResult,
)
from ui.pages.report import _build_clearance_template


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _audio(title: str = "My Track", artist: str = "My Artist") -> AudioBuffer:
    return AudioBuffer(
        raw=b"\x00" * 44,
        sample_rate=22_050,
        label="test",
        metadata={"title": title, "artist": artist},
        source="file",
    )


def _minimal_result(**kwargs) -> AnalysisResult:
    """Minimal result — all optional stages None unless overridden."""
    return AnalysisResult(audio=_audio(), **kwargs)


def _full_result() -> AnalysisResult:
    compliance = ComplianceReport(
        sting=StingResult(ending_type="sting", sync_ready=True, final_energy_ratio=0.04, flag=False),
        evolution=EnergyEvolutionResult(stagnant_windows=0, total_windows=10, flag=False),
        intro=IntroResult(intro_seconds=8.0, flag=False),
    )
    quality = AudioQualityResult(
        integrated_lufs=-14.0,
        true_peak_dbfs=-1.0,
        loudness_range_lu=7.0,
        delta_spotify=0.5,
        delta_apple_music=-2.0,
        delta_youtube=0.5,
        delta_broadcast=-8.5,
        true_peak_warning=False,
        dialogue_score=0.75,
        dialogue_label="Dialogue-Ready",
    )
    popularity = PopularityResult(
        listeners=100_000,
        playcount=500_000,
        spotify_score=60,
        popularity_score=60,
        tier="Mainstream",
        sync_cost_low=10_000,
        sync_cost_high=50_000,
    )
    legal = LegalLinks(
        ascap="https://ascap.com/q=test",
        bmi="https://bmi.com/q=test",
        sesac="https://sesac.com/q=test",
        isrc="US-AB1-23-00001",
        pro_match="ASCAP/BMI (US)",
    )
    return AnalysisResult(
        audio=_audio(),
        compliance=compliance,
        audio_quality=quality,
        popularity=popularity,
        legal=legal,
    )


# ---------------------------------------------------------------------------
# All fields present
# ---------------------------------------------------------------------------

class TestFullResult:
    def setup_method(self):
        self.tmpl = _build_clearance_template(_full_result())

    def test_contains_title(self):
        assert "My Track" in self.tmpl

    def test_contains_artist(self):
        assert "My Artist" in self.tmpl

    def test_contains_tier(self):
        assert "Mainstream" in self.tmpl

    def test_contains_fee_range(self):
        assert "$10,000" in self.tmpl
        assert "$50,000" in self.tmpl

    def test_contains_isrc(self):
        assert "US-AB1-23-00001" in self.tmpl

    def test_contains_pro(self):
        assert "ASCAP/BMI (US)" in self.tmpl

    def test_sync_readiness_all_pass(self):
        assert "Sting ✓" in self.tmpl
        assert "Energy ✓" in self.tmpl
        assert "Intro ✓" in self.tmpl

    def test_dialogue_label(self):
        assert "Dialogue-Ready" in self.tmpl

    def test_footer(self):
        assert "Generated by Sync-Safe" in self.tmpl

    def test_returns_string(self):
        assert isinstance(self.tmpl, str)


# ---------------------------------------------------------------------------
# All optional stages None
# ---------------------------------------------------------------------------

class TestMinimalResult:
    def setup_method(self):
        self.tmpl = _build_clearance_template(_minimal_result())

    def test_no_crash(self):
        assert isinstance(self.tmpl, str)

    def test_tier_fallback(self):
        assert "Unknown" in self.tmpl

    def test_fee_fallback(self):
        assert "not available" in self.tmpl

    def test_isrc_fallback(self):
        assert "not provided" in self.tmpl

    def test_pro_fallback(self):
        assert "unknown" in self.tmpl

    def test_readiness_fallback(self):
        assert "not run" in self.tmpl

    def test_dialogue_fallback(self):
        assert "not run" in self.tmpl

    def test_footer_always_present(self):
        assert "Generated by Sync-Safe" in self.tmpl


# ---------------------------------------------------------------------------
# Individual stage absent
# ---------------------------------------------------------------------------

class TestMissingStages:
    def test_no_pop_fee_fallback(self):
        tmpl = _build_clearance_template(_minimal_result())
        assert "not available" in tmpl

    def test_no_legal_isrc_fallback(self):
        tmpl = _build_clearance_template(_minimal_result())
        assert "not provided" in tmpl

    def test_no_comp_readiness_fallback(self):
        tmpl = _build_clearance_template(_minimal_result())
        assert "not run" in tmpl

    def test_no_aq_dialogue_fallback(self):
        tmpl = _build_clearance_template(_minimal_result())
        assert "not run" in tmpl

    def test_compliance_flags_shown(self):
        compliance = ComplianceReport(
            sting=StingResult(ending_type="cut", sync_ready=False, final_energy_ratio=0.0, flag=True),
            evolution=EnergyEvolutionResult(stagnant_windows=3, total_windows=10, flag=True),
            intro=IntroResult(intro_seconds=20.0, flag=True),
        )
        tmpl = _build_clearance_template(_minimal_result(compliance=compliance))
        assert "Sting ✗" in tmpl
        assert "Energy ✗" in tmpl
        assert "Intro ✗" in tmpl


# ---------------------------------------------------------------------------
# Metadata edge cases
# ---------------------------------------------------------------------------

class TestMetadataEdgeCases:
    def test_empty_title_fallback(self):
        result = AnalysisResult(audio=_audio(title="", artist="Artist"))
        tmpl = _build_clearance_template(result)
        assert "Unknown Track" in tmpl

    def test_empty_artist_fallback(self):
        result = AnalysisResult(audio=_audio(title="Title", artist=""))
        tmpl = _build_clearance_template(result)
        assert "Unknown Artist" in tmpl
