"""
tests/test_tag_injector.py
Unit tests for services/tag_injector.py.

tag_injector.inject() requires mutagen to process real audio bytes.
For pure-function tests (_build_tag_values, _detect_format) no audio is needed.
The integration test (inject roundtrip) uses a real minimal MP3 generated by mutagen.
"""
from __future__ import annotations

import io

import pytest

from core.models import (
    AnalysisResult,
    AudioBuffer,
    ComplianceFlag,
    ComplianceReport,
    EnergyEvolutionResult,
    ForensicsResult,
    IntroResult,
    StingResult,
)
from services.tag_injector import (
    TagInjector,
    _AI_VERDICTS,
    _build_tag_values,
    _detect_format,
)


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

def _make_result(
    grade: str = "A",
    ai_probability: float = 0.1,
    verdict: str = "Likely Not AI",
    flags: list[ComplianceFlag] | None = None,
) -> AnalysisResult:
    compliance = ComplianceReport(
        flags=flags or [],
        sting=StingResult(ending_type="fade", sync_ready=True, final_energy_ratio=0.1),
        evolution=EnergyEvolutionResult(stagnant_windows=0, total_windows=8, detail=""),
        intro=IntroResult(intro_seconds=4.0),
        grade=grade,
    )
    forensics = ForensicsResult(
        ai_probability=ai_probability,
        verdict=verdict,  # type: ignore[arg-type]
    )
    return AnalysisResult(
        audio=AudioBuffer(raw=b"\x00" * 44, label="Test Track.mp3"),
        compliance=compliance,
        forensics=forensics,
    )


# ---------------------------------------------------------------------------
# _detect_format
# ---------------------------------------------------------------------------

class TestDetectFormat:
    def test_id3_header(self) -> None:
        assert _detect_format(b"ID3" + b"\x00" * 100) == "mp3"

    def test_mp3_sync_frame(self) -> None:
        # 0xFF 0xFB = MPEG1 Layer3 128kbps stereo sync word
        assert _detect_format(b"\xff\xfb" + b"\x00" * 100) == "mp3"

    def test_flac_magic(self) -> None:
        assert _detect_format(b"fLaC" + b"\x00" * 100) == "flac"

    def test_ogg_magic(self) -> None:
        assert _detect_format(b"OggS" + b"\x00" * 100) == "ogg"

    def test_unknown_returns_none(self) -> None:
        assert _detect_format(b"\x00" * 100) is None

    def test_empty_returns_none(self) -> None:
        assert _detect_format(b"") is None


# ---------------------------------------------------------------------------
# _build_tag_values
# ---------------------------------------------------------------------------

class TestBuildTagValues:
    def test_keys_present(self) -> None:
        tags = _build_tag_values(_make_result())
        for key in ("SYNC_SAFE_VERSION", "SYNC_SAFE_VERDICT", "SYNC_SAFE_AI_PROBABILITY",
                    "SYNC_SAFE_FLAGS", "SYNC_SAFE_SCAN_DATE", "SYNC_SAFE_SUMMARY"):
            assert key in tags

    def test_verdict_pass_for_good_result(self) -> None:
        tags = _build_tag_values(_make_result(grade="A", verdict="Likely Not AI"))
        assert tags["SYNC_SAFE_VERDICT"] == "PASS"

    def test_verdict_fail_for_bad_grade(self) -> None:
        tags = _build_tag_values(_make_result(grade="F"))
        assert tags["SYNC_SAFE_VERDICT"] == "FAIL"

    def test_verdict_fail_for_ai_content(self) -> None:
        tags = _build_tag_values(_make_result(grade="B", verdict="Likely AI"))
        assert tags["SYNC_SAFE_VERDICT"] == "FAIL"

    def test_verdict_caution_for_mid_grade(self) -> None:
        tags = _build_tag_values(_make_result(grade="C", verdict="Likely Not AI"))
        assert tags["SYNC_SAFE_VERDICT"] == "CAUTION"

    def test_flags_none_when_no_flags(self) -> None:
        tags = _build_tag_values(_make_result())
        assert tags["SYNC_SAFE_FLAGS"] == "none"

    def test_flags_listed_when_present(self) -> None:
        flag = ComplianceFlag(
            timestamp_s=10, issue_type="EXPLICIT",
            text="bad", recommendation="remove",
        )
        tags = _build_tag_values(_make_result(flags=[flag]))
        assert "EXPLICIT" in tags["SYNC_SAFE_FLAGS"]

    def test_ai_probability_formatted(self) -> None:
        tags = _build_tag_values(_make_result(ai_probability=0.345))
        assert tags["SYNC_SAFE_AI_PROBABILITY"] == "34.5"

    def test_scan_date_is_iso8601(self) -> None:
        import re
        tags = _build_tag_values(_make_result())
        assert re.match(r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z", tags["SYNC_SAFE_SCAN_DATE"])

    def test_no_compliance_does_not_crash(self) -> None:
        result = AnalysisResult(audio=AudioBuffer(raw=b"\x00" * 44, label="x"))
        tags   = _build_tag_values(result)
        assert tags["SYNC_SAFE_VERDICT"] == "CAUTION"  # no grade → neither PASS nor FAIL

    def test_summary_contains_grade(self) -> None:
        tags = _build_tag_values(_make_result(grade="B"))
        assert "Grade: B" in tags["SYNC_SAFE_SUMMARY"]


# ---------------------------------------------------------------------------
# TagInjector.inject — unknown format falls back to original bytes
# ---------------------------------------------------------------------------

class TestTagInjectorFallback:
    def test_unknown_format_returns_original(self) -> None:
        audio  = b"\x00" * 200  # not a recognisable format
        result = _make_result()
        out    = TagInjector().inject(audio, result)
        assert out == audio

    def test_empty_bytes_returns_original(self) -> None:
        out = TagInjector().inject(b"", _make_result())
        assert out == b""


# ---------------------------------------------------------------------------
# TagInjector.inject — MP3 roundtrip (requires a real ID3-capable MP3)
# ---------------------------------------------------------------------------

def _make_minimal_mp3() -> bytes:
    """
    Create a minimal MP3 with an empty ID3 header using mutagen.
    Falls back to None if mutagen is not installed.
    """
    try:
        from mutagen.id3 import ID3  # type: ignore[import]
    except ImportError:
        return b""

    buf = io.BytesIO()
    id3 = ID3()
    id3.save(buf, v2_version=3)
    # Append a minimal valid MPEG sync frame so mutagen recognises it as MP3
    buf.write(b"\xff\xfb\x90\x00" + b"\x00" * 413)  # 417-byte MPEG1 frame
    buf.seek(0)
    return buf.read()


class TestTagInjectorMp3:
    def test_inject_adds_txxx_frames(self) -> None:
        mp3 = _make_minimal_mp3()
        if not mp3:
            pytest.skip("mutagen not installed")

        result = _make_result(grade="A")
        tagged = TagInjector().inject(mp3, result)

        from mutagen.id3 import ID3  # type: ignore[import]
        id3 = ID3(io.BytesIO(tagged))
        txxx_descs = [frame.desc for frame in id3.getall("TXXX")]
        assert "SYNC_SAFE_VERDICT" in txxx_descs
        assert "SYNC_SAFE_VERSION" in txxx_descs

    def test_inject_adds_comm_frame(self) -> None:
        mp3 = _make_minimal_mp3()
        if not mp3:
            pytest.skip("mutagen not installed")

        tagged = TagInjector().inject(mp3, _make_result())
        from mutagen.id3 import ID3  # type: ignore[import]
        id3    = ID3(io.BytesIO(tagged))
        comm   = id3.getall("COMM")
        assert any(c.desc == "Sync-Safe Report" for c in comm)

    def test_inject_result_is_larger_than_original(self) -> None:
        mp3 = _make_minimal_mp3()
        if not mp3:
            pytest.skip("mutagen not installed")

        tagged = TagInjector().inject(mp3, _make_result())
        assert len(tagged) >= len(mp3)
