# Generated by Django 5.2.13 on 2026-04-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0003_analysis_label"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(db_index=True, default=0),
                ),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
    ]
